@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE0MjU4Mjg4LCJleHAiOjE3MTY4NTAyODh9.dOokTc9B79DdOUkK7Ne5DL85A-JOl9Cc3LXqR_3nlVc

### Add participant
POST http://localhost:1337/api/Participants HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "data": {
        "name": "Nome Completo",
        "email": "email@email.com",
        "meeting": 23,
        "confirmed": false
    }
}
